export const artistsData = [
  {
    id: '1',
    name: 'Vincent Mnxombola',
    specialty: 'Artist',
    handle: '@vincent_mnxombola',
    image: '/imgs/artist1.jpg',
    description: 'For Appointment Bookings Contact:0727503212✍🏾Tattoo,Drawings.',
    instagram: 'https://instagram.com/dylanbrownink',
    gallery: ['/gallery/jordan1.jpg', '/gallery/jordan2.jpg', '/gallery/jordan3.jpg', '/gallery/jordan4.jpg', 
    '/gallery/jordan5.jpg', '/gallery/jordan6.jpg', '/gallery/jordan7.jpg', '/gallery/jordan8.jpg'],
  },
  {
    id: '2',
    name: 'Thabo Makgatho',
    specialty: 'Artist',
    handle: '@thabo_makgatho',
    image: '/imgs/artist2.jpg',
    description: 'Tattoo Artist 🇿🇦Proclaimed Neighbourhood Scratcha Enquiry & Appointment: WHATSAPP: 0814071917',
    instagram: 'https://instagram.com/olivianorthcolor',
    gallery: ['/gallery/jordan1.jpg', '/gallery/jordan2.jpg', '/gallery/jordan3.jpg', '/gallery/jordan4.jpg', 
    '/gallery/jordan5.jpg', '/gallery/jordan6.jpg', '/gallery/jordan7.jpg', '/gallery/jordan8.jpg'],
  },
  {
    id: '3',
    name: 'Jamie Michelle Van Aswegen',
    specialty: 'Artist',
    handle: '@jamie_michelle_vanaswegen',
    image: '/imgs/artist3.jpg',
    description: 'Tattoo Apprentice (Capital Park) Flesh N Ink Tattoos.',
    instagram: 'https://instagram.com/sofiagrantportrait',
    gallery: ['/gallery/sam1.jpg', '/gallery/sam2.jpg', '/gallery/sam3.jpg'],
  },
];
